### ISSUE TITLE
Wrapping issue in left sidebar of the website

### ISSUE THREAD

**Issue by geekygirldawn** [corsa-center/corsa-center.github.io#2]
On smaller screens (like my MacBook Pro), the text at the top of the sidebar (the CORSA Description and GH link) overlaps with the text aligned to the bottom of page in the sidebar ("This project is maintained ...). 

Here's a screenshot of the overlap. 

<img width="357" alt="image" src="https://github.com/corsa-center/corsa-center.github.io/assets/1304299/5b61f9c7-af1b-47dd-be57-c2ce01d5ad76">

If I move the window to my large monitor and increase the vertical size of the window, the overlap goes away and looks just fine.

**Comment by jarrah42** [comment]
I can reproduce it by shrinking the height of the page until the "Hosted on GitHub Pages..." part overlaps. It must be a bug in this theme.

**Comment by danielskatz** [comment]
I can't duplicate this on my mac using Safari... though I can with Firefox

**Comment by jarrah42** [comment]
New website should solve this.
